version: "3"

services:
  web:
    build: './'
    container_name: gb-projectile
    restart: always
    # network_mode: "bridge"
    env_file:
     - ./.env
    ports:
      - "3006:3000"
    volumes:
      - "./:/usr/src/app"
      - "/usr/src/app/node_modules"